### ISSUE TITLE
Why publish ruby package to npm!?

### ISSUE THREAD

**Issue by tracker1** [sureshpandiyan1/whaly#1]
Why would you publish a ruby script to npm?!?  There's no guarantee that someone with npm/node (especially in windows) has ruby installed or configured, or is running an environment that can even use a bash/shell script.

Beyond this, node/npm has a concept of "binary" modules to add the command when you do a global/local install.  This is just so wrong in so many ways.

https://guides.rubygems.org/publishing/

**Comment by sureshpandiyan1** [comment]
Okey, I clearly understand what you are trying to say about npm.. You are right..
